### PR TITLE
change the way to import edb namespace into edm by introducing poetry

### PR DESCRIPTION
**Pull request by nsidnev**
This should help wtih #7.

Changes in python EDM:
1. Add EdgeDB as git submodule dependency.
2. Add poetry for readable and maintanable dependencies specification.
3. Add isort and black and apply them.
4. Add custom CI workflow.

### CODE REVIEW

**Review by dmgolembiowski — COMMENTED** [review]
Looks good

**Comment by tailhook** [comment]
Have you considered just applying the schema into the live EdgeDB and then using [introspection](https://www.edgedb.com/docs/edgeql/introspection/index) for getting type info for making codegen? Or do you use edgedb submodule for different purposes?

**Comment by dmgolembiowski** [comment]
> Have you considered applying the schema into the live EdgeDB and then using [introspection](https://www.edgedb.com/docs/edgeql/introspection/index) for getting type info for making codegen? Or do you use edgedb submodule for different purposes?

No, I hadn't considered that. Thanks for the suggestion; it may come in handy once I begin the `edm` port to rust. I chose this approach because back when alpha-1 or alpha-2 and I was just getting started, I realized it wasn't convenient enough to check syntax for validity unless you were already on the CLI. 
At those earlier versions, the error reporting was less refined than it is now, so debugging was a chore.

But for compilation I'm using the _edgedb.edb_ submodule to deserialize a user's module files into AST so that only valid schemas can be "installed".

For the time being, it's a smelly to hack the non-public submodule into edgemorph, but it's only temporary :slightly_smiling_face:

**Comment by tailhook** [comment]
Oh, I've seen this comment after commenting about the same in another issue. You may disregard that comment.

**Pull request merged**
